libname hw6 "C:\Users\kurt chuang\Desktop\SAS\lesson6\";
proc print data=hw6.statpack107fhw6;
run;
data hw6a;
set hw6.statpack107fhw6;
firstdate_n=input(firstdate,yymmdd8.);
indate_n=input(indate,yymmdd8.);
format firstdate_n  yymmdd8.
			indate_n yymmdd8.;
run;
proc print data= hw6a;
run;
data hw6b;
set hw6.statpack107fhw6;
first=mdy(input(substr(firstdate,5,2),2.),input(substr(firstdate,7,2),2.),input(substr(firstdate,1,4),4.));
birth=mdy(input(substr(left(ID_BIRTHDAY),5,2),2.),input(substr(left(ID_BIRTHDAY),7,2),2.),input(substr(left(ID_BIRTHDAY),1,4),4.));
thr_day=round((first-birth)/365.25);
run;
proc print data= hw6b;
run;
proc means data=hw6b Q1 median Q3;
var thr_day;
run;
data hw6c;
set hw6b;
 if thr_day<=53 then GP1='第一群';
if 53< thr_day<=64 then GP1='第二群';
if 64<thr_day<=72 then GP1='第三群';
else GP1='第四群';
label
GP1='年齡群組';
run;
proc print data=hw6c LABEL;
run;
data hw6d;
set hw6b;
today=today();
thr_day=today-first;
run;
proc print data= hw6d;
data hw6f;
set hw6.statpack107fhw6;
var1=scan( icd_code,1,',');
var2=scan( icd_code,2,',');
var3=scan( icd_code,3,',');
var4=scan( icd_code,4,',');
var5=scan( icd_code,5,',');
run;
proc print data=hw6f;
run;
data hw6g;
set  hw6f;
array old var1 var2 var3 var4 var5; 
array new nvar1 nvar2 nvar3 nvar4 nvar5; 
	do i=1 to 5;
		new{i}=input(substr(left(old{i}),1,3),3.);
	end;
			do i=1 to 5;
				if new{i}=457 or  new{i}=458 or  new{i}=484 or  new{i}=485 or  new{i}=486   then  sugery='有做手術';
				else sugery='沒做手術';
			end;
				do i=1 to 5;
					if old{i}=9925   then  chem='有做化療';
					else chem='沒做化療';
				end;

proc print data=hw6g;
run;

proc freq data= hw6c ;
tables GP1;
run;
proc means data= hw6d  MEDIAN STD MEAN;
var thr_day;
run;
proc freq data= hw6g ;
tables sugery*chem;
run;
